openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /api/v1/user:
    post:
      summary: Crea un nuevo usuario
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '200':
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
components:
  schemas:
    CreateUserRequest:
      type: object
      properties:
        name:
          type: string
        lastname:
          type: string
        alias:
          type: string
        address:
          type: string
        phone:
          type: string
        accountType:
          type: string
    CreateUserResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        bankAccount:
          $ref: '#/components/schemas/BankAccount'
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        lastname:
          type: string
        alias:
          type: string
        address:
          type: string
        phone:
          type: string
        authId:
          type: string
    BankAccount:
      type: object
      properties:
        id:
          type: string
        type_account_id:
          type: string
        user_id:
          type: string
        number_account:
          type: string
        balance:
          type: number
